dialogue change @e[tag=trade_hay_block_4_TO_emerald_1,type=npc,c=1] trade_hay_block_4_TO_emerald_1_X0 @a[hasitem={item=hay_block, quantity=0..3}]
dialogue change @e[tag=trade_hay_block_4_TO_emerald_1,type=npc,c=1] trade_hay_block_4_TO_emerald_1_X1 @a[hasitem={item=hay_block, quantity=4..15}]
dialogue change @e[tag=trade_hay_block_4_TO_emerald_1,type=npc,c=1] trade_hay_block_4_TO_emerald_1_X4 @a[hasitem={item=hay_block, quantity=16..63}]
dialogue change @e[tag=trade_hay_block_4_TO_emerald_1,type=npc,c=1] trade_hay_block_4_TO_emerald_1_X16 @a[hasitem={item=hay_block, quantity=64..255}]
dialogue change @e[tag=trade_hay_block_4_TO_emerald_1,type=npc,c=1] trade_hay_block_4_TO_emerald_1_X64 @a[hasitem={item=hay_block, quantity=256..575}]
dialogue change @e[tag=trade_hay_block_4_TO_emerald_1,type=npc,c=1] trade_hay_block_4_TO_emerald_1_X144 @a[hasitem={item=hay_block, quantity=576..}]

dialogue change @e[tag=trade_iron_ingot_4_TO_emerald_1,type=npc,c=1] trade_iron_ingot_4_TO_emerald_1_X0 @a[hasitem={item=iron_ingot, quantity=0..3}]
dialogue change @e[tag=trade_iron_ingot_4_TO_emerald_1,type=npc,c=1] trade_iron_ingot_4_TO_emerald_1_X1 @a[hasitem={item=iron_ingot, quantity=4..15}]
dialogue change @e[tag=trade_iron_ingot_4_TO_emerald_1,type=npc,c=1] trade_iron_ingot_4_TO_emerald_1_X4 @a[hasitem={item=iron_ingot, quantity=16..63}]
dialogue change @e[tag=trade_iron_ingot_4_TO_emerald_1,type=npc,c=1] trade_iron_ingot_4_TO_emerald_1_X16 @a[hasitem={item=iron_ingot, quantity=64..255}]
dialogue change @e[tag=trade_iron_ingot_4_TO_emerald_1,type=npc,c=1] trade_iron_ingot_4_TO_emerald_1_X64 @a[hasitem={item=iron_ingot, quantity=256..575}]
dialogue change @e[tag=trade_iron_ingot_4_TO_emerald_1,type=npc,c=1] trade_iron_ingot_4_TO_emerald_1_X144 @a[hasitem={item=iron_ingot, quantity=576..}]

dialogue change @e[tag=trade_diamond_1_TO_emerald_2,type=npc,c=1] trade_diamond_1_TO_emerald_2_X0 @a[hasitem={item=diamond, quantity=0..0}]
dialogue change @e[tag=trade_diamond_1_TO_emerald_2,type=npc,c=1] trade_diamond_1_TO_emerald_2_X1 @a[hasitem={item=diamond, quantity=1..3}]
dialogue change @e[tag=trade_diamond_1_TO_emerald_2,type=npc,c=1] trade_diamond_1_TO_emerald_2_X4 @a[hasitem={item=diamond, quantity=4..15}]
dialogue change @e[tag=trade_diamond_1_TO_emerald_2,type=npc,c=1] trade_diamond_1_TO_emerald_2_X16 @a[hasitem={item=diamond, quantity=16..63}]
dialogue change @e[tag=trade_diamond_1_TO_emerald_2,type=npc,c=1] trade_diamond_1_TO_emerald_2_X64 @a[hasitem={item=diamond, quantity=64..255}]
dialogue change @e[tag=trade_diamond_1_TO_emerald_2,type=npc,c=1] trade_diamond_1_TO_emerald_2_X256 @a[hasitem={item=diamond, quantity=256..}]

dialogue change @e[tag=trade_gold_ingot_4_TO_emerald_1,type=npc,c=1] trade_gold_ingot_4_TO_emerald_1_X0 @a[hasitem={item=gold_ingot, quantity=0..3}]
dialogue change @e[tag=trade_gold_ingot_4_TO_emerald_1,type=npc,c=1] trade_gold_ingot_4_TO_emerald_1_X1 @a[hasitem={item=gold_ingot, quantity=4..15}]
dialogue change @e[tag=trade_gold_ingot_4_TO_emerald_1,type=npc,c=1] trade_gold_ingot_4_TO_emerald_1_X4 @a[hasitem={item=gold_ingot, quantity=16..63}]
dialogue change @e[tag=trade_gold_ingot_4_TO_emerald_1,type=npc,c=1] trade_gold_ingot_4_TO_emerald_1_X16 @a[hasitem={item=gold_ingot, quantity=64..255}]
dialogue change @e[tag=trade_gold_ingot_4_TO_emerald_1,type=npc,c=1] trade_gold_ingot_4_TO_emerald_1_X64 @a[hasitem={item=gold_ingot, quantity=256..575}]
dialogue change @e[tag=trade_gold_ingot_4_TO_emerald_1,type=npc,c=1] trade_gold_ingot_4_TO_emerald_1_X144 @a[hasitem={item=gold_ingot, quantity=576..}]

dialogue change @e[tag=trade_lapis_lazuli_8_TO_emerald_1,type=npc,c=1] trade_lapis_lazuli_8_TO_emerald_1_X0 @a[hasitem={item=lapis_lazuli, quantity=0..7}]
dialogue change @e[tag=trade_lapis_lazuli_8_TO_emerald_1,type=npc,c=1] trade_lapis_lazuli_8_TO_emerald_1_X1 @a[hasitem={item=lapis_lazuli, quantity=8..31}]
dialogue change @e[tag=trade_lapis_lazuli_8_TO_emerald_1,type=npc,c=1] trade_lapis_lazuli_8_TO_emerald_1_X4 @a[hasitem={item=lapis_lazuli, quantity=32..127}]
dialogue change @e[tag=trade_lapis_lazuli_8_TO_emerald_1,type=npc,c=1] trade_lapis_lazuli_8_TO_emerald_1_X16 @a[hasitem={item=lapis_lazuli, quantity=128..511}]
dialogue change @e[tag=trade_lapis_lazuli_8_TO_emerald_1,type=npc,c=1] trade_lapis_lazuli_8_TO_emerald_1_X64 @a[hasitem={item=lapis_lazuli, quantity=512..1151}]
dialogue change @e[tag=trade_lapis_lazuli_8_TO_emerald_1,type=npc,c=1] trade_lapis_lazuli_8_TO_emerald_1_X144 @a[hasitem={item=lapis_lazuli, quantity=1152..}]

dialogue change @e[tag=trade_baked_potato_28_TO_emerald_1,type=npc,c=1] trade_baked_potato_28_TO_emerald_1_X0 @a[hasitem={item=baked_potato, quantity=0..27}]
dialogue change @e[tag=trade_baked_potato_28_TO_emerald_1,type=npc,c=1] trade_baked_potato_28_TO_emerald_1_X1 @a[hasitem={item=baked_potato, quantity=28..111}]
dialogue change @e[tag=trade_baked_potato_28_TO_emerald_1,type=npc,c=1] trade_baked_potato_28_TO_emerald_1_X4 @a[hasitem={item=baked_potato, quantity=112..223}]
dialogue change @e[tag=trade_baked_potato_28_TO_emerald_1,type=npc,c=1] trade_baked_potato_28_TO_emerald_1_X8 @a[hasitem={item=baked_potato, quantity=224..447}]
dialogue change @e[tag=trade_baked_potato_28_TO_emerald_1,type=npc,c=1] trade_baked_potato_28_TO_emerald_1_X16 @a[hasitem={item=baked_potato, quantity=448..895}]
dialogue change @e[tag=trade_baked_potato_28_TO_emerald_1,type=npc,c=1] trade_baked_potato_28_TO_emerald_1_X32 @a[hasitem={item=baked_potato, quantity=896..}]

dialogue change @e[tag=trade_carrot_32_TO_emerald_1,type=npc,c=1] trade_carrot_32_TO_emerald_1_X0 @a[hasitem={item=carrot, quantity=0..31}]
dialogue change @e[tag=trade_carrot_32_TO_emerald_1,type=npc,c=1] trade_carrot_32_TO_emerald_1_X1 @a[hasitem={item=carrot, quantity=32..127}]
dialogue change @e[tag=trade_carrot_32_TO_emerald_1,type=npc,c=1] trade_carrot_32_TO_emerald_1_X4 @a[hasitem={item=carrot, quantity=128..255}]
dialogue change @e[tag=trade_carrot_32_TO_emerald_1,type=npc,c=1] trade_carrot_32_TO_emerald_1_X8 @a[hasitem={item=carrot, quantity=256..511}]
dialogue change @e[tag=trade_carrot_32_TO_emerald_1,type=npc,c=1] trade_carrot_32_TO_emerald_1_X16 @a[hasitem={item=carrot, quantity=512..1023}]
dialogue change @e[tag=trade_carrot_32_TO_emerald_1,type=npc,c=1] trade_carrot_32_TO_emerald_1_X32 @a[hasitem={item=carrot, quantity=1024..}]

dialogue change @e[tag=trade_melon_block_8_TO_emerald_1,type=npc,c=1] trade_melon_block_8_TO_emerald_1_X0 @a[hasitem={item=melon_block, quantity=0..7}]
dialogue change @e[tag=trade_melon_block_8_TO_emerald_1,type=npc,c=1] trade_melon_block_8_TO_emerald_1_X1 @a[hasitem={item=melon_block, quantity=8..31}]
dialogue change @e[tag=trade_melon_block_8_TO_emerald_1,type=npc,c=1] trade_melon_block_8_TO_emerald_1_X4 @a[hasitem={item=melon_block, quantity=32..127}]
dialogue change @e[tag=trade_melon_block_8_TO_emerald_1,type=npc,c=1] trade_melon_block_8_TO_emerald_1_X16 @a[hasitem={item=melon_block, quantity=128..255}]
dialogue change @e[tag=trade_melon_block_8_TO_emerald_1,type=npc,c=1] trade_melon_block_8_TO_emerald_1_X32 @a[hasitem={item=melon_block, quantity=256..511}]
dialogue change @e[tag=trade_melon_block_8_TO_emerald_1,type=npc,c=1] trade_melon_block_8_TO_emerald_1_X64 @a[hasitem={item=melon_block, quantity=512..}]

dialogue change @e[tag=trade_oak_log_16_TO_emerald_1,type=npc,c=1] trade_oak_log_16_TO_emerald_1_X0 @a[hasitem={item=oak_log, quantity=0..15}]
dialogue change @e[tag=trade_oak_log_16_TO_emerald_1,type=npc,c=1] trade_oak_log_16_TO_emerald_1_X1 @a[hasitem={item=oak_log, quantity=16..63}]
dialogue change @e[tag=trade_oak_log_16_TO_emerald_1,type=npc,c=1] trade_oak_log_16_TO_emerald_1_X4 @a[hasitem={item=oak_log, quantity=64..255}]
dialogue change @e[tag=trade_oak_log_16_TO_emerald_1,type=npc,c=1] trade_oak_log_16_TO_emerald_1_X16 @a[hasitem={item=oak_log, quantity=256..511}]
dialogue change @e[tag=trade_oak_log_16_TO_emerald_1,type=npc,c=1] trade_oak_log_16_TO_emerald_1_X32 @a[hasitem={item=oak_log, quantity=512..1023}]
dialogue change @e[tag=trade_oak_log_16_TO_emerald_1,type=npc,c=1] trade_oak_log_16_TO_emerald_1_X64 @a[hasitem={item=oak_log, quantity=1024..}]