dialogue change @e[tag=trade_hay_block_4_TO_emerald_1,type=npc,c=1] trade_hay_block_4_TO_emerald_1_X0 @a[hasitem={item=hay_block, quantity=0..3}]
dialogue change @e[tag=trade_hay_block_4_TO_emerald_1,type=npc,c=1] trade_hay_block_4_TO_emerald_1_X1 @a[hasitem={item=hay_block, quantity=4..15}]
dialogue change @e[tag=trade_hay_block_4_TO_emerald_1,type=npc,c=1] trade_hay_block_4_TO_emerald_1_X4 @a[hasitem={item=hay_block, quantity=16..63}]
dialogue change @e[tag=trade_hay_block_4_TO_emerald_1,type=npc,c=1] trade_hay_block_4_TO_emerald_1_X16 @a[hasitem={item=hay_block, quantity=64..255}]
dialogue change @e[tag=trade_hay_block_4_TO_emerald_1,type=npc,c=1] trade_hay_block_4_TO_emerald_1_X64 @a[hasitem={item=hay_block, quantity=256..575}]
dialogue change @e[tag=trade_hay_block_4_TO_emerald_1,type=npc,c=1] trade_hay_block_4_TO_emerald_1_X144 @a[hasitem={item=hay_block, quantity=576..}]

dialogue change @e[tag=trade_iron_ingot_4_TO_emerald_1,type=npc,c=1] trade_iron_ingot_4_TO_emerald_1_X0 @a[hasitem={item=iron_ingot, quantity=0..3}]
dialogue change @e[tag=trade_iron_ingot_4_TO_emerald_1,type=npc,c=1] trade_iron_ingot_4_TO_emerald_1_X1 @a[hasitem={item=iron_ingot, quantity=4..15}]
dialogue change @e[tag=trade_iron_ingot_4_TO_emerald_1,type=npc,c=1] trade_iron_ingot_4_TO_emerald_1_X4 @a[hasitem={item=iron_ingot, quantity=16..63}]
dialogue change @e[tag=trade_iron_ingot_4_TO_emerald_1,type=npc,c=1] trade_iron_ingot_4_TO_emerald_1_X16 @a[hasitem={item=iron_ingot, quantity=64..255}]
dialogue change @e[tag=trade_iron_ingot_4_TO_emerald_1,type=npc,c=1] trade_iron_ingot_4_TO_emerald_1_X64 @a[hasitem={item=iron_ingot, quantity=256..575}]
dialogue change @e[tag=trade_iron_ingot_4_TO_emerald_1,type=npc,c=1] trade_iron_ingot_4_TO_emerald_1_X144 @a[hasitem={item=iron_ingot, quantity=576..}]

dialogue change @e[tag=trade_diamond_1_TO_emerald_2,type=npc,c=1] trade_diamond_1_TO_emerald_2_X0 @a[hasitem={item=diamond, quantity=0..0}]
dialogue change @e[tag=trade_diamond_1_TO_emerald_2,type=npc,c=1] trade_diamond_1_TO_emerald_2_X1 @a[hasitem={item=diamond, quantity=1..3}]
dialogue change @e[tag=trade_diamond_1_TO_emerald_2,type=npc,c=1] trade_diamond_1_TO_emerald_2_X4 @a[hasitem={item=diamond, quantity=4..15}]
dialogue change @e[tag=trade_diamond_1_TO_emerald_2,type=npc,c=1] trade_diamond_1_TO_emerald_2_X16 @a[hasitem={item=diamond, quantity=16..63}]
dialogue change @e[tag=trade_diamond_1_TO_emerald_2,type=npc,c=1] trade_diamond_1_TO_emerald_2_X64 @a[hasitem={item=diamond, quantity=64..255}]
dialogue change @e[tag=trade_diamond_1_TO_emerald_2,type=npc,c=1] trade_diamond_1_TO_emerald_2_X256 @a[hasitem={item=diamond, quantity=256..}]

dialogue change @e[tag=trade_gold_ingot_4_TO_emerald_1,type=npc,c=1] trade_gold_ingot_4_TO_emerald_1_X0 @a[hasitem={item=gold_ingot, quantity=0..3}]
dialogue change @e[tag=trade_gold_ingot_4_TO_emerald_1,type=npc,c=1] trade_gold_ingot_4_TO_emerald_1_X1 @a[hasitem={item=gold_ingot, quantity=4..15}]
dialogue change @e[tag=trade_gold_ingot_4_TO_emerald_1,type=npc,c=1] trade_gold_ingot_4_TO_emerald_1_X4 @a[hasitem={item=gold_ingot, quantity=16..63}]
dialogue change @e[tag=trade_gold_ingot_4_TO_emerald_1,type=npc,c=1] trade_gold_ingot_4_TO_emerald_1_X16 @a[hasitem={item=gold_ingot, quantity=64..255}]
dialogue change @e[tag=trade_gold_ingot_4_TO_emerald_1,type=npc,c=1] trade_gold_ingot_4_TO_emerald_1_X64 @a[hasitem={item=gold_ingot, quantity=256..575}]
dialogue change @e[tag=trade_gold_ingot_4_TO_emerald_1,type=npc,c=1] trade_gold_ingot_4_TO_emerald_1_X144 @a[hasitem={item=gold_ingot, quantity=576..}]

dialogue change @e[tag=trade_lapis_lazuli_8_TO_emerald_1,type=npc,c=1] trade_lapis_lazuli_8_TO_emerald_1_X0 @a[hasitem={item=lapis_lazuli, quantity=0..7}]
dialogue change @e[tag=trade_lapis_lazuli_8_TO_emerald_1,type=npc,c=1] trade_lapis_lazuli_8_TO_emerald_1_X1 @a[hasitem={item=lapis_lazuli, quantity=8..31}]
dialogue change @e[tag=trade_lapis_lazuli_8_TO_emerald_1,type=npc,c=1] trade_lapis_lazuli_8_TO_emerald_1_X4 @a[hasitem={item=lapis_lazuli, quantity=32..127}]
dialogue change @e[tag=trade_lapis_lazuli_8_TO_emerald_1,type=npc,c=1] trade_lapis_lazuli_8_TO_emerald_1_X16 @a[hasitem={item=lapis_lazuli, quantity=128..511}]
dialogue change @e[tag=trade_lapis_lazuli_8_TO_emerald_1,type=npc,c=1] trade_lapis_lazuli_8_TO_emerald_1_X64 @a[hasitem={item=lapis_lazuli, quantity=512..1151}]
dialogue change @e[tag=trade_lapis_lazuli_8_TO_emerald_1,type=npc,c=1] trade_lapis_lazuli_8_TO_emerald_1_X144 @a[hasitem={item=lapis_lazuli, quantity=1152..}]

dialogue change @e[tag=trade_baked_potato_28_TO_emerald_1,type=npc,c=1] trade_baked_potato_28_TO_emerald_1_X0 @a[hasitem={item=baked_potato, quantity=0..27}]
dialogue change @e[tag=trade_baked_potato_28_TO_emerald_1,type=npc,c=1] trade_baked_potato_28_TO_emerald_1_X1 @a[hasitem={item=baked_potato, quantity=28..111}]
dialogue change @e[tag=trade_baked_potato_28_TO_emerald_1,type=npc,c=1] trade_baked_potato_28_TO_emerald_1_X4 @a[hasitem={item=baked_potato, quantity=112..223}]
dialogue change @e[tag=trade_baked_potato_28_TO_emerald_1,type=npc,c=1] trade_baked_potato_28_TO_emerald_1_X8 @a[hasitem={item=baked_potato, quantity=224..447}]
dialogue change @e[tag=trade_baked_potato_28_TO_emerald_1,type=npc,c=1] trade_baked_potato_28_TO_emerald_1_X16 @a[hasitem={item=baked_potato, quantity=448..895}]
dialogue change @e[tag=trade_baked_potato_28_TO_emerald_1,type=npc,c=1] trade_baked_potato_28_TO_emerald_1_X32 @a[hasitem={item=baked_potato, quantity=896..}]

dialogue change @e[tag=trade_carrot_32_TO_emerald_1,type=npc,c=1] trade_carrot_32_TO_emerald_1_X0 @a[hasitem={item=carrot, quantity=0..31}]
dialogue change @e[tag=trade_carrot_32_TO_emerald_1,type=npc,c=1] trade_carrot_32_TO_emerald_1_X1 @a[hasitem={item=carrot, quantity=32..127}]
dialogue change @e[tag=trade_carrot_32_TO_emerald_1,type=npc,c=1] trade_carrot_32_TO_emerald_1_X4 @a[hasitem={item=carrot, quantity=128..255}]
dialogue change @e[tag=trade_carrot_32_TO_emerald_1,type=npc,c=1] trade_carrot_32_TO_emerald_1_X8 @a[hasitem={item=carrot, quantity=256..511}]
dialogue change @e[tag=trade_carrot_32_TO_emerald_1,type=npc,c=1] trade_carrot_32_TO_emerald_1_X16 @a[hasitem={item=carrot, quantity=512..1023}]
dialogue change @e[tag=trade_carrot_32_TO_emerald_1,type=npc,c=1] trade_carrot_32_TO_emerald_1_X32 @a[hasitem={item=carrot, quantity=1024..}]

dialogue change @e[tag=trade_melon_block_8_TO_emerald_1,type=npc,c=1] trade_melon_block_8_TO_emerald_1_X0 @a[hasitem={item=melon_block, quantity=0..7}]
dialogue change @e[tag=trade_melon_block_8_TO_emerald_1,type=npc,c=1] trade_melon_block_8_TO_emerald_1_X1 @a[hasitem={item=melon_block, quantity=8..31}]
dialogue change @e[tag=trade_melon_block_8_TO_emerald_1,type=npc,c=1] trade_melon_block_8_TO_emerald_1_X4 @a[hasitem={item=melon_block, quantity=32..127}]
dialogue change @e[tag=trade_melon_block_8_TO_emerald_1,type=npc,c=1] trade_melon_block_8_TO_emerald_1_X16 @a[hasitem={item=melon_block, quantity=128..255}]
dialogue change @e[tag=trade_melon_block_8_TO_emerald_1,type=npc,c=1] trade_melon_block_8_TO_emerald_1_X32 @a[hasitem={item=melon_block, quantity=256..511}]
dialogue change @e[tag=trade_melon_block_8_TO_emerald_1,type=npc,c=1] trade_melon_block_8_TO_emerald_1_X64 @a[hasitem={item=melon_block, quantity=512..}]

dialogue change @e[tag=trade_stick_128_TO_emerald_1,type=npc,c=1] trade_stick_128_TO_emerald_1_X0 @a[hasitem={item=stick, quantity=0..127}]
dialogue change @e[tag=trade_stick_128_TO_emerald_1,type=npc,c=1] trade_stick_128_TO_emerald_1_X1 @a[hasitem={item=stick, quantity=128..255}]
dialogue change @e[tag=trade_stick_128_TO_emerald_1,type=npc,c=1] trade_stick_128_TO_emerald_1_X2 @a[hasitem={item=stick, quantity=256..511}]
dialogue change @e[tag=trade_stick_128_TO_emerald_1,type=npc,c=1] trade_stick_128_TO_emerald_1_X4 @a[hasitem={item=stick, quantity=512..1023}]
dialogue change @e[tag=trade_stick_128_TO_emerald_1,type=npc,c=1] trade_stick_128_TO_emerald_1_X8 @a[hasitem={item=stick, quantity=1024..1791}]
dialogue change @e[tag=trade_stick_128_TO_emerald_1,type=npc,c=1] trade_stick_128_TO_emerald_1_X14 @a[hasitem={item=stick, quantity=1792..}]

dialogue change @e[tag=trade_emerald_1_TO_iron_ingot_3,type=npc,c=1] trade_emerald_1_TO_iron_ingot_3_X0 @a[hasitem={item=emerald, quantity=0..0}]
dialogue change @e[tag=trade_emerald_1_TO_iron_ingot_3,type=npc,c=1] trade_emerald_1_TO_iron_ingot_3_X1 @a[hasitem={item=emerald, quantity=1..3}]
dialogue change @e[tag=trade_emerald_1_TO_iron_ingot_3,type=npc,c=1] trade_emerald_1_TO_iron_ingot_3_X4 @a[hasitem={item=emerald, quantity=4..15}]
dialogue change @e[tag=trade_emerald_1_TO_iron_ingot_3,type=npc,c=1] trade_emerald_1_TO_iron_ingot_3_X16 @a[hasitem={item=emerald, quantity=16..63}]
dialogue change @e[tag=trade_emerald_1_TO_iron_ingot_3,type=npc,c=1] trade_emerald_1_TO_iron_ingot_3_X64 @a[hasitem={item=emerald, quantity=64..143}]
dialogue change @e[tag=trade_emerald_1_TO_iron_ingot_3,type=npc,c=1] trade_emerald_1_TO_iron_ingot_3_X144 @a[hasitem={item=emerald, quantity=144..}]

dialogue change @e[tag=trade_emerald_7_TO_diamond_3,type=npc,c=1] trade_emerald_7_TO_diamond_3_X0 @a[hasitem={item=emerald, quantity=0..6}]
dialogue change @e[tag=trade_emerald_7_TO_diamond_3,type=npc,c=1] trade_emerald_7_TO_diamond_3_X1 @a[hasitem={item=emerald, quantity=7..27}]
dialogue change @e[tag=trade_emerald_7_TO_diamond_3,type=npc,c=1] trade_emerald_7_TO_diamond_3_X4 @a[hasitem={item=emerald, quantity=28..111}]
dialogue change @e[tag=trade_emerald_7_TO_diamond_3,type=npc,c=1] trade_emerald_7_TO_diamond_3_X16 @a[hasitem={item=emerald, quantity=112..447}]
dialogue change @e[tag=trade_emerald_7_TO_diamond_3,type=npc,c=1] trade_emerald_7_TO_diamond_3_X64 @a[hasitem={item=emerald, quantity=448..1007}]
dialogue change @e[tag=trade_emerald_7_TO_diamond_3,type=npc,c=1] trade_emerald_7_TO_diamond_3_X144 @a[hasitem={item=emerald, quantity=1008..}]

dialogue change @e[tag=trade_emerald_1_TO_gold_ingot_3,type=npc,c=1] trade_emerald_1_TO_gold_ingot_3_X0 @a[hasitem={item=emerald, quantity=0..0}]
dialogue change @e[tag=trade_emerald_1_TO_gold_ingot_3,type=npc,c=1] trade_emerald_1_TO_gold_ingot_3_X1 @a[hasitem={item=emerald, quantity=1..3}]
dialogue change @e[tag=trade_emerald_1_TO_gold_ingot_3,type=npc,c=1] trade_emerald_1_TO_gold_ingot_3_X4 @a[hasitem={item=emerald, quantity=4..15}]
dialogue change @e[tag=trade_emerald_1_TO_gold_ingot_3,type=npc,c=1] trade_emerald_1_TO_gold_ingot_3_X16 @a[hasitem={item=emerald, quantity=16..63}]
dialogue change @e[tag=trade_emerald_1_TO_gold_ingot_3,type=npc,c=1] trade_emerald_1_TO_gold_ingot_3_X64 @a[hasitem={item=emerald, quantity=64..143}]
dialogue change @e[tag=trade_emerald_1_TO_gold_ingot_3,type=npc,c=1] trade_emerald_1_TO_gold_ingot_3_X144 @a[hasitem={item=emerald, quantity=144..}]

dialogue change @e[tag=trade_emerald_2_TO_lapis_lazuli_12,type=npc,c=1] trade_emerald_2_TO_lapis_lazuli_12_X0 @a[hasitem={item=emerald, quantity=0..1}]
dialogue change @e[tag=trade_emerald_2_TO_lapis_lazuli_12,type=npc,c=1] trade_emerald_2_TO_lapis_lazuli_12_X1 @a[hasitem={item=emerald, quantity=2..7}]
dialogue change @e[tag=trade_emerald_2_TO_lapis_lazuli_12,type=npc,c=1] trade_emerald_2_TO_lapis_lazuli_12_X4 @a[hasitem={item=emerald, quantity=8..31}]
dialogue change @e[tag=trade_emerald_2_TO_lapis_lazuli_12,type=npc,c=1] trade_emerald_2_TO_lapis_lazuli_12_X16 @a[hasitem={item=emerald, quantity=32..127}]
dialogue change @e[tag=trade_emerald_2_TO_lapis_lazuli_12,type=npc,c=1] trade_emerald_2_TO_lapis_lazuli_12_X64 @a[hasitem={item=emerald, quantity=128..287}]
dialogue change @e[tag=trade_emerald_2_TO_lapis_lazuli_12,type=npc,c=1] trade_emerald_2_TO_lapis_lazuli_12_X144 @a[hasitem={item=emerald, quantity=288..}]

dialogue change @e[tag=trade_emerald_5_TO_golden_carrot_16,type=npc,c=1] trade_emerald_5_TO_golden_carrot_16_X0 @a[hasitem={item=emerald, quantity=0..4}]
dialogue change @e[tag=trade_emerald_5_TO_golden_carrot_16,type=npc,c=1] trade_emerald_5_TO_golden_carrot_16_X1 @a[hasitem={item=emerald, quantity=5..19}]
dialogue change @e[tag=trade_emerald_5_TO_golden_carrot_16,type=npc,c=1] trade_emerald_5_TO_golden_carrot_16_X4 @a[hasitem={item=emerald, quantity=20..79}]
dialogue change @e[tag=trade_emerald_5_TO_golden_carrot_16,type=npc,c=1] trade_emerald_5_TO_golden_carrot_16_X16 @a[hasitem={item=emerald, quantity=80..319}]
dialogue change @e[tag=trade_emerald_5_TO_golden_carrot_16,type=npc,c=1] trade_emerald_5_TO_golden_carrot_16_X64 @a[hasitem={item=emerald, quantity=320..719}]
dialogue change @e[tag=trade_emerald_5_TO_golden_carrot_16,type=npc,c=1] trade_emerald_5_TO_golden_carrot_16_X144 @a[hasitem={item=emerald, quantity=720..}]

dialogue change @e[tag=trade_emerald_5_TO_experience_bottle_64,type=npc,c=1] trade_emerald_5_TO_experience_bottle_64_X0 @a[hasitem={item=emerald, quantity=0..4}]
dialogue change @e[tag=trade_emerald_5_TO_experience_bottle_64,type=npc,c=1] trade_emerald_5_TO_experience_bottle_64_X1 @a[hasitem={item=emerald, quantity=5..19}]
dialogue change @e[tag=trade_emerald_5_TO_experience_bottle_64,type=npc,c=1] trade_emerald_5_TO_experience_bottle_64_X4 @a[hasitem={item=emerald, quantity=20..79}]
dialogue change @e[tag=trade_emerald_5_TO_experience_bottle_64,type=npc,c=1] trade_emerald_5_TO_experience_bottle_64_X16 @a[hasitem={item=emerald, quantity=80..}]

dialogue change @e[tag=trade_emerald_3_TO_empty_map_1,type=npc,c=1] trade_emerald_3_TO_empty_map_1_X0 @a[hasitem={item=emerald, quantity=0..2}]
dialogue change @e[tag=trade_emerald_3_TO_empty_map_1,type=npc,c=1] trade_emerald_3_TO_empty_map_1_X1 @a[hasitem={item=emerald, quantity=3..5}]
dialogue change @e[tag=trade_emerald_3_TO_empty_map_1,type=npc,c=1] trade_emerald_3_TO_empty_map_1_X2 @a[hasitem={item=emerald, quantity=6..11}]
dialogue change @e[tag=trade_emerald_3_TO_empty_map_1,type=npc,c=1] trade_emerald_3_TO_empty_map_1_X4 @a[hasitem={item=emerald, quantity=12..}]

dialogue change @e[tag=trade_emerald_64_TO_netherite_scrap_1,type=npc,c=1] trade_emerald_64_TO_netherite_scrap_1_X0 @a[hasitem={item=emerald, quantity=0..63}]
dialogue change @e[tag=trade_emerald_64_TO_netherite_scrap_1,type=npc,c=1] trade_emerald_64_TO_netherite_scrap_1_X1 @a[hasitem={item=emerald, quantity=64..255}]
dialogue change @e[tag=trade_emerald_64_TO_netherite_scrap_1,type=npc,c=1] trade_emerald_64_TO_netherite_scrap_1_X4 @a[hasitem={item=emerald, quantity=256..1023}]
dialogue change @e[tag=trade_emerald_64_TO_netherite_scrap_1,type=npc,c=1] trade_emerald_64_TO_netherite_scrap_1_X16 @a[hasitem={item=emerald, quantity=1024..}]

dialogue change @e[tag=trade_emerald_8_TO_mending_enchant_1,type=npc,c=1] trade_emerald_8_TO_mending_enchant_1_X0 @a[hasitem=[{item=emerald, quantity=0..7},{location=slot.weapon.mainhand,item=book,quantity=!1}]]
dialogue change @e[tag=trade_emerald_8_TO_mending_enchant_1,type=npc,c=1] trade_emerald_8_TO_mending_enchant_1_X1 @a[hasitem=[{item=emerald, quantity=8..},{location=slot.weapon.mainhand,item=book,quantity=1}]]

dialogue change @e[tag=trade_emerald_20_TO_unbreaking_enchant_1,type=npc,c=1] trade_emerald_20_TO_unbreaking_enchant_1_X0 @a[hasitem=[{item=emerald, quantity=0..19},{location=slot.weapon.mainhand,item=book,quantity=!1}]]
dialogue change @e[tag=trade_emerald_20_TO_unbreaking_enchant_1,type=npc,c=1] trade_emerald_20_TO_unbreaking_enchant_1_X1 @a[hasitem=[{item=emerald, quantity=20..},{location=slot.weapon.mainhand,item=book,quantity=1}]]

dialogue change @e[tag=trade_emerald_20_TO_netherite_upgrade_smithing_template_1,type=npc,c=1] trade_emerald_20_TO_netherite_upgrade_smithing_template_1_X0 @a[hasitem={item=emerald, quantity=0..19}]
dialogue change @e[tag=trade_emerald_20_TO_netherite_upgrade_smithing_template_1,type=npc,c=1] trade_emerald_20_TO_netherite_upgrade_smithing_template_1_X1 @a[hasitem={item=emerald, quantity=20..39}]
dialogue change @e[tag=trade_emerald_20_TO_netherite_upgrade_smithing_template_1,type=npc,c=1] trade_emerald_20_TO_netherite_upgrade_smithing_template_1_X2 @a[hasitem={item=emerald, quantity=40..79}]
dialogue change @e[tag=trade_emerald_20_TO_netherite_upgrade_smithing_template_1,type=npc,c=1] trade_emerald_20_TO_netherite_upgrade_smithing_template_1_X4 @a[hasitem={item=emerald, quantity=80..}]